/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambdas;

import com.google.common.collect.Lists;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args) {
        //Data test
        List<Movie> movies = Lists.newArrayList(
                new Movie(1L, "Goodfellas", "Martin Scorsese", LocalDate.of(1990, 9, 19), 1990),
                new Movie(1L, "Casino", "Martin Scorsese", LocalDate.of(1995, 4, 3), 1995),
                new Movie(1L, "Scarface", "Brian de Palma", LocalDate.of(1983, 12, 1), 1983),
                new Movie(1L, "Legend", "Brian Helgeland", LocalDate.of(2016, 1, 8), 2016)
        );

        movies.forEach(System.out::println);


    }
}
